#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y			:= cetusplus_debug.o cetusplus_setup.o cetusplus_timer.o cetusplus_intc.o cetusplus_misc.o
obj-m			:=
obj-n			:=
obj-			:=

obj-$(CONFIG_PCI) += cetusplus_pci.o

